Pages/Doctor/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDoctor.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace USI_PROJEKAT.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesAccount.Models;
using RazorPagesAccount.Services;
using System.ComponentModel.DataAnnotations;

namespace USI_PROJEKAT.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }
    [BindProperty]
    public Credentials Cred { get; set; } = new Credentials();
    
    public Account Current { get; set; }
    public void OnGet()
    {
    
    }
    public IActionResult OnPost()
    {
        if(AccountService.LogIn(Cred.Username,Cred.Password) != -1)
        {
           Current = AccountService.Get(AccountService.LogIn(Cred.Username,Cred.Password)); //refactor this somehow, also the app should know which user is logged in via the id
           switch(Current.Type){
                case AccountType.Manager:
                    return Redirect("Manager"); 
                case AccountType.Doctor:
                    return Redirect("Doctor");
                case AccountType.Patient:
                    return Redirect("Patient");
                case AccountType.Secretary:
                    return Redirect("Secretary");
           }
        }
        return null;
    }
    public class Credentials 
    {
    [Required]
    [Display(Name ="Email address")]
    public string Username {get; set;} = "";
    [Required]
    [DataType(DataType.Password)]
    public string Password {get; set;} = "";
    }
}

Pages/Manager/CRUDHospitalRooms.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHospitalRoom.Models;
using RazorPagesHospitalRoom.Services;

namespace RazorPagesManager.Pages
{
    public class CRUDHospitalRoomsModel : PageModel
    {
        
        public List<HospitalRoom> rooms = new();
        public void OnGet()
        {
            rooms = HospitalRoomService.GetAll();
        }
        
        public IActionResult OnPostDelete(int id)
        {
            HospitalRoomService.Delete(id);
            return RedirectToAction("Get");
        }
        
    }
}

Pages/Manager/CreateHospitalRooms.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHospitalRoom.Models;
using RazorPagesHospitalRoom.Services;

namespace RazorPagesManager.Pages
{
    public class CreateHospitalRoomsModel : PageModel

    {
        [BindProperty]
        public HospitalRoom NewRoom { get; set; } = new();
        public IActionResult  OnGet()
        {
            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            HospitalRoomService.Add(NewRoom);
            return Redirect("CRUDHospitalRooms");
        }
    }
}

Pages/Manager/EditHospitalRooms.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHospitalRoom.Models;
using RazorPagesHospitalRoom.Services;

namespace RazorPagesManager.Pages
{
    public class EditHospitalRoomsModel : PageModel
    {
        [BindProperty]
        public HospitalRoom? Hr {get;set;}
        public IActionResult OnGet(int id)
        {
            Hr = HospitalRoomService.Get(id);

            if (Hr == null)
            {
                return NotFound();
            }
            return Page();
        }
        public IActionResult OnPost(int id)
        { 
            HospitalRoomService.Update(id,Hr.Name,Hr.Type);
            return Redirect("CRUDHospitalRooms");
        }
    }
}

Pages/Manager/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesManager.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnPostCRUDHospitalRooms()
        {
            return Redirect("Manager/CRUDHospitalRooms");
        }
        public IActionResult OnPostManagerEquipment()
        {
            return Redirect("Manager/ManagerEquipment");
        }
    }
}

Pages/Manager/ManagerEquipment.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHospitalEquipment.Models;
using RazorPagesHospitalRoom.Models;
using RazorPagesHospitalEquipment.Services;
using System.ComponentModel.DataAnnotations;

namespace RazorPagesManager.Pages
{
    public class ManagerEquipmentModel : PageModel
    {
        [BindProperty]
        public SearchTerms STerms { get; set; } = new SearchTerms();
        public List<HospitalEquipment> Results {get; set;} = new List<HospitalEquipment>();
        
        public void OnGet()
        {
            Results = HospitalEquipmentService.GetAll();
        }
        public void OnPost()
        {
            if (STerms.SearchTerm is not null)
            {
                Results = HospitalEquipmentService.Search(STerms.SearchTerm);
            }
            else
            {
                Results = HospitalEquipmentService.GetAll();
            }
            if (STerms.FilterByEqTypeBool == true)
            {
                Results = HospitalEquipmentService.FilterByEqType(Results, STerms.FilterByEq);
            }
            if (STerms.FilterByRoomTypeBool == true)
            {
                Results = HospitalEquipmentService.FilterByRoomType(Results, STerms.FilterByRoom);
            }
            if (STerms.FilterByAmountBool == true)
            {
                switch(STerms.STAmount)
                {
                    case Amount.Zero:
                        Results = HospitalEquipmentService.FilterByNumbers(Results,0,0);
                        break;
                    case Amount.OneToTen:
                        Results = HospitalEquipmentService.FilterByNumbers(Results,1,10);
                        break;
                    case Amount.AboveTen:
                        Results = HospitalEquipmentService.FilterByNumbers(Results,11,10000000);
                        break;
                }
            }

        }
        public class SearchTerms 
        {
        public string SearchTerm { get; set; }
        public bool FilterByEqTypeBool { get; set; }
        public EquipmentType FilterByEq { get; set; }
        public bool FilterByAmountBool { get; set; }
        public Amount STAmount { get; set; }
        public bool FilterByRoomTypeBool { get; set; }
        public RoomType FilterByRoom { get; set; }
        }
        public enum Amount { Zero, OneToTen, AboveTen }
        
    }
}

Pages/Patient/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagePatient.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace USI_PROJEKAT.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Secretary/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesSecretary.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Doctor/Index.cshtml
@page
@model RazorPagesDoctor.Pages.IndexModel
@{
    ViewData["Title"] = "Doctor";
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <div class="row d-flex justify-content-center">
        <form class="col-md-6" method="post">
        <!-- Email input -->
            <div class="form-outline mb-4">
                <input type="email" id="form2Example1" asp-for="Cred.Username" class="form-control" />
                <label class="form-label" asp-for="Cred.Username" for="form2Example1">Email address</label>
                <span class="text-danger" asp-validation-for="Cred.Username"></span>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                <input type="password" id="form2Example2" asp-for="Cred.Password" class="form-control" />
                <label class="form-label" asp-for="Cred.Password" for="form2Example2">Password</label>
                <span class="text-danger" asp-validation-for="Cred.Password"></span>
            </div>

            <!-- 2 column grid layout for inline styling -->
            <div class="row mb-4">
                <div class="col d-flex justify-content-center">
                <!-- Checkbox -->
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                    <label class="form-check-label" for="form2Example31"> Remember me </label>
                </div>
                </div>

                <div class="col">
                <!-- Simple link -->
                <a href="#!">Forgot password?</a>
                </div>
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
        </form>
    </div>
</div>

Pages/Manager/CRUDHospitalRooms.cshtml
@page
@using RazorPagesHospitalRoom.Models;
@model RazorPagesManager.Pages.CRUDHospitalRoomsModel
@{
    ViewData["Title"] = "Manage Hospital Rooms";
}
<div id="modal-placeholder"></div>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-5">
						<h2>Manage <b>Hospital Rooms</b></h2>
					</div>
					<div class="col-sm-5">
						<a asp-page="./CreateHospitalRooms" type="btn" class="btn btn-success">Add New Room</a>						
					</div>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Name</th>
						<th>Type</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
                    @foreach (var room in Model.rooms)
                    {
                        <tr>
						<td>@room.Name</td>
						<td>@room.Type</td>
                        <td>
                            <a onclick="if(@room.Id==0){return confirm('You cannot edit or delete Storage!')}" asp-page="./EditHospitalRooms" asp-route-id="@room.Id" class="edit"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                        </td>
						<td>
                            <form asp-page-handler="Delete" asp-route-id="@room.Id">
                                <button type="btn" class="text-danger ml-1" onclick="if(@room.Id==0){return confirm('You cannot edit or delete Storage!')}else return confirm('Are you sure you want to delete this record?\nThis is irreversible!')"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></button>
                            </form>
                        </td>
					</tr>
                    }
				</tbody>
			</table>
		</div>
	</div>        
</div>
@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

Pages/Manager/CreateHospitalRooms.cshtml
@page
@using RazorPagesHospitalRoom.Models;
@model RazorPagesManager.Pages.CreateHospitalRoomsModel;
@{
     ViewData["Title"] = "Create new Hospital Room";
}

<div class="container">
    <div class="row ">
        <div class="col-md-6 offset-md-3">
            <form method="POST">
                <legend>Create A New Room</legend>
                <div class="mb-3">
                    <label for="txtName" class="form-label">Name</label>
                    <input asp-for="NewRoom.Name" type="text" class="form-control" id="txtName" />
                </div>
                <div class="mb-3">
                    <label asp-for="NewRoom.Type">Type</label>
                    <select asp-for="NewRoom.Type" asp-items="Html.GetEnumSelectList<RoomType>()" class="mr-5"></select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
 
    </div>
 
</div>

Pages/Manager/EditHospitalRooms.cshtml
@page
@using RazorPagesHospitalRoom.Models;
@model RazorPagesManager.Pages.EditHospitalRoomsModel
@{
     ViewData["Title"] = "Edit Hospital Room";
}

<div class="container">
    <div class="row ">
        <div class="col-md-6 offset-md-3">
            <form method="POST">
                <legend>Edit A Room</legend>
                <div class="mb-3">
                    <label for="txtName" class="form-label">Name</label>
                    <input asp-for="Hr.Name" type="text" class="form-control" id="txtName" />
                </div>
                <div class="mb-3">
                    <label asp-for="Hr.Type">Type</label>
                    <select asp-for="Hr.Type" asp-items="Html.GetEnumSelectList<RoomType>()" class="mr-5"></select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
 
    </div>
 
</div>

Pages/Manager/Index.cshtml
@page
@model RazorPagesManager.Pages.IndexModel
@{
    ViewData["Title"] = "Manager";
}

<div class="text-center">
    <h1 class="display-4">Welcome, @DateTime.Now</h1>
    <table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Manager menu</th>

        </tr>
    </thead>
    
        <tr>
            <td>Manage hospital rooms</td>
            <td>
                <form method="post" asp-page-handler="CRUDHospitalRooms" asp-route-id="">
                    <button class="btn btn-primary">Go</button>
                </form>
            </td>
        </tr>
        <tr>
            <td>Manage hospital equipment</td>
            <td>
                <form method="post" asp-page-handler="ManagerEquipment" asp-route-id="">
                    <button class="btn btn-primary">Go</button>
                </form>
            </td>
        </tr>
    
</table>
</div>

Pages/Manager/ManagerEquipment.cshtml
@page
@using RazorPagesHospitalEquipment.Models;
@using RazorPagesHospitalRoom.Models;
@using RazorPagesHospitalRoom.Services;
@model RazorPagesManager.Pages.ManagerEquipmentModel;
@{
}

<div>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <label asp-for="STerms.SearchTerm">Search</label>
        <input type="text" asp-for="STerms.SearchTerm" class="mr-5">
        <label asp-for="STerms.FilterByEqTypeBool">Filter By Equipment Type</label>
        <input type="checkbox" asp-for="STerms.FilterByEqTypeBool" class="mr-5">
        <select asp-for="STerms.FilterByEq" asp-items="Html.GetEnumSelectList<EquipmentType>()" class="mr-5"></select>
        <label asp-for="STerms.FilterByRoomTypeBool">Filter By Room Type</label>
        <input type="checkbox" asp-for="STerms.FilterByRoomTypeBool" class="mr-5">
        <select asp-for="STerms.FilterByRoom" asp-items="Html.GetEnumSelectList<RoomType>()" class="mr-5"></select>
        <label asp-for="STerms.FilterByAmountBool">Filter By Amount</label>
        <input type="checkbox" asp-for="STerms.FilterByAmountBool" class="mr-5">
        <select asp-for="STerms.STAmount" asp-items="Html.GetEnumSelectList<RazorPagesManager.Pages.ManagerEquipmentModel.Amount>()" class="mr-5"></select>
        <button class="btn btn-primary">Search</button>
    </div>
    </form>
    <table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Room</th>
            <th scope="col">Room Type</th>
            <th scope="col">Equipment Type</th>
            <th scope="col">Edit</th>
        </tr>
    </thead>
    @foreach (var item in Model.Results)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Amount</td>
            <td>@HospitalRoomService.Get(item.RoomId).Name</td>
            <td>@HospitalRoomService.Get(item.RoomId).Type</td>
            <td>@item.Type</td>
            <td>
                <a asp-page="./EditHospitalRooms" asp-route-id="@item.Id" class="edit"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
            </td>
        </tr>
    }
</table>
</div>

Pages/Patient/Index.cshtml
@page
@model RazorPagePatient.Pages.IndexModel
@{
}

Pages/Secretary/Index.cshtml
@page
@model RazorPagesSecretary.Pages.IndexModel
@{
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - USI_PROJEKAT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/USI_PROJEKAT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">USI_PROJEKAT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>